
const receta2 = new receta("Tea", "Milk", "Cinammon")
const receta3 = new receta("Tea", "Tea", "Milk")
const receta4 = new receta("Tea", "Tea", "Lemon")
const receta5 = new receta("Tea", "Mint", "Tea")
const receta6 = new receta("Tea", "Tea", "Mint")
const receta7 = new receta("Tea", "Cinammon", "Honey")
const receta8 = new receta("Milk", "Cinammon", "Cinammon")
const receta9 = new receta("Tea", "Tea", "Honey" )
const receta10 = new receta("Tea","Ginger", "Honey")